Move SQL utilities from bgbb_lib
wcbeard/bgbb_airflow pull request #7
Opened 2019-11-19 18:41 UTC by acmiyaguchi

This moved most of the application-like code from bgbb_lib into this repo, so it can be migrated to a GCP workflow.

2019-11-22 16:33 UTC, wcbeard requested changes
All good, except for a question on `fit_airflow_job.py`

2019-11-22 16:33 UTC, wcbeard commented on bgbb_airflow/fit_airflow_job.py
> -import bgbb_airflow
Won't this break the ` bgbb_airflow.__version__` in line 114 below?

2019-11-22 19:34 UTC, acmiyaguchi commented on bgbb_airflow/fit_airflow_job.py
> -import bgbb_airflow
Yes, this will. I'll run the jobs manually to double check that this PR won't break the current workflow.

2019-11-22 19:37 UTC, acmiyaguchi commented
```
./bin/run-databricks \
    --token ${DB_TOKEN} \
    --git-path https://github.com/acmiyaguchi/bgbb_airflow.git \
    --git-branch sql-utils \
    bgbb_fit \
        --submission-date 2019-11-01 \
        --prefix bgbb/param/v1 \
        --bucket telemetry-test-bucket
```
https://dbc-caf9527b-e073.cloud.databricks.com/#job/5184/run/1

```
./bin/run-databricks \
    --token ${DB_TOKEN} \
    --git-path https://github.com/acmiyaguchi/bgbb_airflow.git \
    --git-branch sql-utils \
    bgbb_pred \
        --submission-date 2019-11-01 \
        --param-bucket telemetry-parquet \
        --param-prefix bgbb/param/v1 \
        --pred-bucket telemetry-test-bucket \
        --pred-prefix bgbb/active_profiles/v1
```
https://dbc-caf9527b-e073.cloud.databricks.com/#job/5183/run/1

2019-11-23 00:15 UTC, acmiyaguchi commented
Both of the jobs successfully completed, this is ready for another look.

2019-11-25 20:46 UTC, wcbeard approved these changes

2019-11-25 20:47 UTC, merged